<?php

namespace CelinaBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * ColorRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ColorRepository extends EntityRepository
{
}
