celina_homepage_en:
    path:     /
    defaults: { _controller: CelinaBundle:DefaultEn:index }

celina_product_list_en:
    path:     /productList/{categoryId}
    defaults: { _controller: CelinaBundle:DefaultEn:productList }

celina_fotodetalle_list_en:
    path:     /fotodetalle/{productId}
    defaults: { _controller: CelinaBundle:DefaultEn:productDetalle }

celina_product_list_new_en:
    path:     /newproductList
    defaults: { _controller: CelinaBundle:DefaultEn:productListNew }