CelinaBundle\Entity\Color:
    type: entity
    table: null
    repositoryClass: CelinaBundle\Repository\ColorRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        colorNameEs:
            type: string
            length: 255
        colorNameEn:
            type: string
            length: 255
        colorFoto:
            type: string
            length: 255
    manyToOne:
        product:
            targetEntity: Product
            inversedBy: colors
            joinColumn:
                name: product_id
                referencedColumnName: id
    lifecycleCallbacks: {  }
