CelinaBundle\Entity\Fotodetalle:
    type: entity
    table: null
    repositoryClass: CelinaBundle\Repository\FotodetalleRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        fotodetalle:
            type: string
            length: 255
        position:
            type: string
            length: 255
    manyToOne:
        product:
            targetEntity: Product
            inversedBy: fotodetalles
            joinColumn:
                name: product_id
                referencedColumnName: id
    lifecycleCallbacks: {  }
